---
stages:
  - test

molecule:
  stage: test
  only:
    - branches
    - merge_requests
  tags:
    - vagrant
  script:
    - ansible-lint $(find . -regex ".*\.\(yml\)")
    - sudo molecule test -s default
