---
- name: Create users for databases
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    role_attr_flags: LOGIN
  become: true
  become_user: "{{ postgresql_admin_user }}"
  with_items:
    - "{{ databases }}"
  when: db is defined

- name: Create databases
  postgresql_db:
    name: "{{ item.name }}"
    state: present
    encoding: "UTF-8"
    lc_collate: "en_US.UTF-8"
    lc_ctype: "en_US.UTF-8"
    template: "template0"
    owner: "{{ item.user }}"
  become: true
  become_user: "{{ postgresql_admin_user }}"
  with_items:
    - "{{ databases }}"
  when: db is defined

- name: Copy dump files in /tmp
  template:
    src: "{{ item.file }}"
    dest: /tmp
  with_items:
    - "{{ dump }}"
  when: dump_restore is defined

- name: Restore dump file in database
  postgresql_db:
    name: "{{ item.db }}"
    state: restore
    target: "/tmp/{{ item.file }}"
  become: true
  become_user: "{{ postgresql_admin_user }}"
  with_items:
    - "{{ dump }}"
  when: dump_restore is defined
