---
# convert 9.6 to 96
- name: Set postgres version
  set_fact:
    pg_ver: "{{ postgresql_version.split('.') | join('') }}"

- name: print
  debug:
    msg: "{{ pg_repo_package }}"

- name: Install postgres repository
  yum:
    name: "{{ pg_repo_package }}"
    state: present

- name: Install depended packages
  yum:
    name:
      - python-psycopg2
      - python-pycurl
      - crontabs
    state: present

- name: Install packages
  yum:
    name:
      - "postgresql{{ pg_ver }}"
      - "postgresql{{ pg_ver }}-server"
    state: present
    update_cache: yes
  notify:
    - restart postgres
    - change admin password

- name: check configuration file
  stat:
    path: /var/lib/pgsql/11/data/pg_wal
  register: config_file

- name: Initialize postgres database
  command: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ pg_ver }}-setup initdb"
  when: not config_file.stat.exists
