---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: instance-centos
    box: centos/7
    memory: 1536
    cpus: 2
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--nictype1', 'virtio' ]"
      - "customize [ 'modifyvm', :id, '--nictype2', 'virtio' ]"
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
      - "customize [ 'modifyvm', :id, '--natdnsproxy1', 'on' ]"
      - "customize [ 'modifyvm', :id, '--ioapic', 'on' ]"

  - name: instance-ubuntu
    box: ubuntu/xenial64
    memory: 1536
    cpus: 2
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--nictype1', 'virtio' ]"
      - "customize [ 'modifyvm', :id, '--nictype2', 'virtio' ]"
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
      - "customize [ 'modifyvm', :id, '--natdnsproxy1', 'on' ]"
      - "customize [ 'modifyvm', :id, '--ioapic', 'on' ]"


provisioner:
  name: ansible
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
